#!/bin/bash

# 11. タブをスペースに置換
# タブ1文字につきスペース1文字に置換せよ.確認にはsedコマンド,trコマンド,もしくはexpandコマンドを用いよ.

cat hightemp.txt | sed s/'\t'/' '/g > hightemp_sed.txt
cat hightemp.txt | tr '\t' ' ' > hightemp_tr.txt
expand -t 1 hightemp.txt > hightemp_expand.txt

diff hightemp_sed.txt hightemp_tr.txt
diff hightemp_tr.txt hightemp_expand.txt