#!/bin/bash

# 12. 1列目をcol1.txtに,2列目をcol2.txtに保存
# 各行の1列目だけを抜き出したものをcol1.txtに,2列目だけを抜き出したものをcol2.txtとしてファイルに保存せよ.確認にはcutコマンドを用いよ.

cut -f 1 hightemp.txt > col1.txt
cut -f 2 hightemp.txt > col2.txt

# 別解
# cat hightemp.txt | awk -F'\t' '{print $1}' > col1.txt
# cat hightemp.txt | awk -F'\t' '{print $2}' > col2.txt
